### ISSUE TITLE
Mods/Items Missing Icon Description

### ISSUE THREAD

**Issue by EvilHogg** [OfficialNeocron/public-bug-tracker#34]
The following weapon mods are missing their icon descriptions (i.e. DMG, FRQ, HND)

DIFERRO-TETRAOXID-LIQUID
ENERGY CORE ENHANCEMENT
ENERGY CORE WEIGHT REDUCTION
PRISM ENHANCER
TITAN-CARBONDICLORID
PSI-MODULE-ENHANCEMENT

![image](https://github.com/OfficialNeocron/public-bug-tracker/assets/34963912/c35d3bba-f22d-4a3c-a10d-f5614e959c2d)

As compared to mods that do have them:

![image](https://github.com/OfficialNeocron/public-bug-tracker/assets/34963912/391ba060-c67f-468b-8d0b-964d78df4ebc)

Suggestions
-Add icon description to Titanium Armor
-Add icon description to NCPD PA obtained from CA epic

**Comment by Virtus-NST** [comment]
I've committed a change to fix these mods and armours, will be shipped to Titan soon - Please test, though :)

**Comment by EvilHogg** [comment]
DIFERRO-TETRAOXID-LIQUID - Correct
ENERGY CORE ENHANCEMENT  - Correct
ENERGY CORE WEIGHT REDUCTION  - Correct
PRISM ENHANCER  - Correct (have not seen D/F before)
TITAN-CARBONDICLORID  - Correct
PSI-MODULE-ENHANCEMENT - Still Missing <----

Titan Armor - Exists
NCPD PA - Exists

Thank you
